; Blade -- generated by the BLADE_LLVM lane (src/EmitLlvm.fs).
; No target triple: clang supplies the host's. Fast-math flags
; appear ONLY on licensed accumulator chains (BLADE_FP_REASSOC)
; and, on request, as per-instruction `contract`
; (BLADE_FP_CONTRACT); default emission is order-preserving.

@.blade.str.0 = private unnamed_addr constant [13 x i8] c"array_reduce\00"
@.blade.str.1 = private unnamed_addr constant [7 x i8] c"xs = [\00"
@.blade.str.2 = private unnamed_addr constant [3 x i8] c", \00"
@.blade.str.3 = private unnamed_addr constant [3 x i8] c"]\0A\00"
@.blade.str.4 = private unnamed_addr constant [12 x i8] c"doubled = [\00"
@.blade.str.5 = private unnamed_addr constant [6 x i8] c"total\00"

declare double @blade_now() #3
declare noalias align 64 ptr @blade_alloc_cells(i64 noundef, i64 noundef) #4
declare void @blade_out_f64(double noundef) #3
declare void @blade_out_str(ptr noundef) #3
declare void @blade_print_completed(ptr noundef, double noundef) #3
declare void @blade_print_f64(ptr noundef, double noundef) #3

define i32 @main() #0 {
entry:
  %r8 = alloca i64
  %r16 = alloca double
  %r22 = alloca double
  %r25 = alloca i64
  %r35 = alloca double
  %r36 = alloca double
  %r43 = alloca double
  %r46 = alloca i1
  %r47 = alloca i64
  %r61 = alloca i1
  %r62 = alloca i64
  %r1 = call double @blade_now()
  %r2 = call ptr @blade_alloc_cells(i64 4, i64 8)
  %r3 = getelementptr inbounds double, ptr %r2, i64 0
  store double 0x3FF0000000000000, ptr %r3
  %r4 = getelementptr inbounds double, ptr %r2, i64 1
  store double 0x4000000000000000, ptr %r4
  %r5 = getelementptr inbounds double, ptr %r2, i64 2
  store double 0x4008000000000000, ptr %r5
  %r6 = getelementptr inbounds double, ptr %r2, i64 3
  store double 0x4010000000000000, ptr %r6
  %r7 = call ptr @blade_alloc_cells(i64 4, i64 8)
  store i64 0, ptr %r8
  br label %loop.cond9
loop.cond9:
  %r12 = load i64, ptr %r8
  %r13 = icmp slt i64 %r12, 4
  br i1 %r13, label %loop.body10, label %loop.end11
loop.body10:
  %r14 = getelementptr inbounds double, ptr %r2, i64 %r12
  %r15 = load double, ptr %r14
  store double %r15, ptr %r16
  %r17 = load double, ptr %r16
  %r18 = fmul double %r17, 0x4000000000000000
  %r19 = getelementptr inbounds double, ptr %r7, i64 %r12
  store double %r18, ptr %r19
  %r20 = load i64, ptr %r8
  %r21 = add i64 %r20, 1
  store i64 %r21, ptr %r8
  br label %loop.cond9
loop.end11:
  %r23 = getelementptr inbounds double, ptr %r7, i64 0
  %r24 = load double, ptr %r23
  store double %r24, ptr %r22
  store i64 0, ptr %r25
  br label %loop.cond26
loop.cond26:
  %r29 = load i64, ptr %r25
  %r30 = icmp slt i64 %r29, 3
  br i1 %r30, label %loop.body27, label %loop.end28
loop.body27:
  %r31 = add i64 %r29, 1
  %r32 = load double, ptr %r22
  %r33 = getelementptr inbounds double, ptr %r7, i64 %r31
  %r34 = load double, ptr %r33
  store double %r32, ptr %r35
  store double %r34, ptr %r36
  %r37 = load double, ptr %r35
  %r38 = load double, ptr %r36
  %r39 = fadd double %r37, %r38
  store double %r39, ptr %r22
  %r40 = load i64, ptr %r25
  %r41 = add i64 %r40, 1
  store i64 %r41, ptr %r25
  br label %loop.cond26
loop.end28:
  %r42 = load double, ptr %r22
  store double %r42, ptr %r43
  %r44 = call double @blade_now()
  %r45 = fsub double %r44, %r1
  call void @blade_print_completed(ptr @.blade.str.0, double %r45)
  call void @blade_out_str(ptr @.blade.str.1)
  store i1 true, ptr %r46
  store i64 0, ptr %r47
  br label %loop.cond48
loop.cond48:
  %r51 = load i64, ptr %r47
  %r52 = icmp slt i64 %r51, 4
  br i1 %r52, label %loop.body49, label %loop.end50
loop.body49:
  %r53 = load i1, ptr %r46
  %r54 = xor i1 %r53, true
  br i1 %r54, label %when.then55, label %when.end56
when.then55:
  call void @blade_out_str(ptr @.blade.str.2)
  br label %when.end56
when.end56:
  store i1 false, ptr %r46
  %r57 = getelementptr inbounds double, ptr %r2, i64 %r51
  %r58 = load double, ptr %r57
  call void @blade_out_f64(double %r58)
  %r59 = load i64, ptr %r47
  %r60 = add i64 %r59, 1
  store i64 %r60, ptr %r47
  br label %loop.cond48
loop.end50:
  call void @blade_out_str(ptr @.blade.str.3)
  call void @blade_out_str(ptr @.blade.str.4)
  store i1 true, ptr %r61
  store i64 0, ptr %r62
  br label %loop.cond63
loop.cond63:
  %r66 = load i64, ptr %r62
  %r67 = icmp slt i64 %r66, 4
  br i1 %r67, label %loop.body64, label %loop.end65
loop.body64:
  %r68 = load i1, ptr %r61
  %r69 = xor i1 %r68, true
  br i1 %r69, label %when.then70, label %when.end71
when.then70:
  call void @blade_out_str(ptr @.blade.str.2)
  br label %when.end71
when.end71:
  store i1 false, ptr %r61
  %r72 = getelementptr inbounds double, ptr %r7, i64 %r66
  %r73 = load double, ptr %r72
  call void @blade_out_f64(double %r73)
  %r74 = load i64, ptr %r62
  %r75 = add i64 %r74, 1
  store i64 %r75, ptr %r62
  br label %loop.cond63
loop.end65:
  call void @blade_out_str(ptr @.blade.str.3)
  %r76 = load double, ptr %r43
  call void @blade_print_f64(ptr @.blade.str.5, double %r76)
  ret i32 0
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn }
attributes #3 = { nofree nounwind willreturn }
attributes #4 = { nofree nounwind }
