; Blade -- generated by the BLADE_LLVM lane (src/EmitLlvm.fs).
; No target triple: clang supplies the host's. Fast-math flags
; appear ONLY on licensed accumulator chains (BLADE_FP_REASSOC)
; and, on request, as per-instruction `contract`
; (BLADE_FP_CONTRACT); default emission is order-preserving.

@.blade.str.0 = private unnamed_addr constant [16 x i8] c"function_branch\00"
@.blade.str.1 = private unnamed_addr constant [4 x i8] c"pos\00"
@.blade.str.2 = private unnamed_addr constant [4 x i8] c"neg\00"

declare double @blade_now() #3
declare void @blade_print_completed(ptr noundef, double noundef) #3
declare void @blade_print_f64(ptr noundef, double noundef) #3

define internal double @bl_classify_0(double noundef %a0) #0 {
entry:
  %r11 = alloca double
  %r14 = alloca double
  store double %a0, ptr %r11
  %r12 = load double, ptr %r11
  %r13 = fcmp ogt double %r12, 0x0000000000000000
  br i1 %r13, label %if.then15, label %if.else16
if.then15:
  %r18 = load double, ptr %r11
  %r19 = fmul double %r18, 0x4000000000000000
  store double %r19, ptr %r14
  br label %if.end17
if.else16:
  %r20 = load double, ptr %r11
  %r21 = fsub double 0x0000000000000000, %r20
  store double %r21, ptr %r14
  br label %if.end17
if.end17:
  %r22 = load double, ptr %r14
  ret double %r22
}

define i32 @main() #0 {
entry:
  %r3 = alloca double
  %r6 = alloca double
  %r1 = call double @blade_now()
  %r2 = call double @bl_classify_0(double 0x400C000000000000)
  store double %r2, ptr %r3
  %r4 = fsub double 0x0000000000000000, 0x4002000000000000
  %r5 = call double @bl_classify_0(double %r4)
  store double %r5, ptr %r6
  %r7 = call double @blade_now()
  %r8 = fsub double %r7, %r1
  call void @blade_print_completed(ptr @.blade.str.0, double %r8)
  %r9 = load double, ptr %r3
  call void @blade_print_f64(ptr @.blade.str.1, double %r9)
  %r10 = load double, ptr %r6
  call void @blade_print_f64(ptr @.blade.str.2, double %r10)
  ret i32 0
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn }
attributes #3 = { nofree nounwind willreturn }
