; Blade -- generated by the BLADE_LLVM lane (src/EmitLlvm.fs).
; No target triple: clang supplies the host's. Fast-math flags
; appear ONLY on licensed accumulator chains (BLADE_FP_REASSOC)
; and, on request, as per-instruction `contract`
; (BLADE_FP_CONTRACT); default emission is order-preserving.

@.blade.str.0 = private unnamed_addr constant [13 x i8] c"scalar_arith\00"
@.blade.str.1 = private unnamed_addr constant [2 x i8] c"a\00"
@.blade.str.2 = private unnamed_addr constant [2 x i8] c"b\00"
@.blade.str.3 = private unnamed_addr constant [5 x i8] c"prod\00"
@.blade.str.4 = private unnamed_addr constant [6 x i8] c"ratio\00"
@.blade.str.5 = private unnamed_addr constant [5 x i8] c"flag\00"

declare double @blade_now() #3
declare void @blade_print_bool(ptr noundef, i32 noundef) #3
declare void @blade_print_completed(ptr noundef, double noundef) #3
declare void @blade_print_f64(ptr noundef, double noundef) #3
declare void @blade_print_i64(ptr noundef, i64 noundef) #3

define i32 @main() #0 {
entry:
  %r2 = alloca i64
  %r3 = alloca i64
  %r7 = alloca i64
  %r9 = alloca double
  %r12 = alloca i1
  %r1 = call double @blade_now()
  store i64 6, ptr %r2
  store i64 7, ptr %r3
  %r4 = load i64, ptr %r2
  %r5 = load i64, ptr %r3
  %r6 = mul i64 %r4, %r5
  store i64 %r6, ptr %r7
  %r8 = fmul double 0x3FF8000000000000, 0x4000000000000000
  store double %r8, ptr %r9
  %r10 = load i64, ptr %r7
  %r11 = icmp sgt i64 %r10, 40
  store i1 %r11, ptr %r12
  %r13 = call double @blade_now()
  %r14 = fsub double %r13, %r1
  call void @blade_print_completed(ptr @.blade.str.0, double %r14)
  %r15 = load i64, ptr %r2
  call void @blade_print_i64(ptr @.blade.str.1, i64 %r15)
  %r16 = load i64, ptr %r3
  call void @blade_print_i64(ptr @.blade.str.2, i64 %r16)
  %r17 = load i64, ptr %r7
  call void @blade_print_i64(ptr @.blade.str.3, i64 %r17)
  %r18 = load double, ptr %r9
  call void @blade_print_f64(ptr @.blade.str.4, double %r18)
  %r19 = load i1, ptr %r12
  %r20 = zext i1 %r19 to i32
  call void @blade_print_bool(ptr @.blade.str.5, i32 %r20)
  ret i32 0
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn }
attributes #3 = { nofree nounwind willreturn }
