// render_video.fsx — a day of Padang radar scans as one video, through the
// Blade + GR lane (examples/radar/padang_20180301.bladenb).
//
// Three steps, all of them the toolchain's own machinery -- no plotting
// library, no image library, no ffmpeg:
//
//   1. GENERATE one Blade program with one plot call per scan against the
//      store make_padang_zarr.fsx wrote. Every frame fixes the colour range
//      with the zmin/zmax slots (stdlib/plot.blade), which is what keeps the
//      scale from flickering scan to scan; each frame's title is its HH:MM.
//   2. `blade run` it ONCE and harvest the display-frame lines from stdout
//      (the \x01blade-display\x01 sentinel, src/display/DisplayFrame.fs).
//      stdout is read as BYTES: the sentinel is a control character, and a
//      text decode mangles it.
//   3. Pipe those specs, one per line, into `gr-render --video`. GR writes
//      the movie itself -- its video plugin is a statically linked ffmpeg --
//      as ONE print session, so there are no intermediate PNGs to encode,
//      flatten and re-encode.
//
// Deliberately loads NOTHING from src/: it drives the built compiler and the
// built helper as processes, and the only store metadata it needs (the scan
// count and the clock) is two small reads. That keeps its startup instant and
// gives it no dependency chain to rot.
//
// Run from anywhere:
//   dotnet fsi examples/radar/render_video.fsx <store.zarr> [--out FILE]
//                [--var rain_rate|rain_zoom] [--fps N] [--width N] [--height N] [--zmax R]
//
// Needs GRDIR set (gr-render's environment contract) and MSYS2 ucrt64 g++ on
// PATH (blade run compiles C++).

open System
open System.Diagnostics
open System.IO
open System.Text
open System.Text.Json

let repo = Path.GetFullPath(Path.Combine(__SOURCE_DIRECTORY__, "..", ".."))
let bladeExe = Path.Combine(repo, "bin", "Release", "net10.0", "Blade.exe")
let grRender = Path.Combine(repo, "tools", "gr-render", "gr-render.exe")
let msysBin = @"C:\msys64\ucrt64\bin"
let sentinel = "\u0001blade-display\u0001"

// ---- arguments ------------------------------------------------------------

let argv = fsi.CommandLineArgs |> Array.skip 1
let positional = argv |> Array.filter (fun a -> not (a.StartsWith "--"))
let opt name dflt =
    match argv |> Array.tryFindIndex ((=) ("--" + name)) with
    | Some i when i + 1 < argv.Length -> argv.[i + 1]
    | _ -> dflt

if positional.Length < 1 then
    eprintfn "usage: dotnet fsi render_video.fsx <store.zarr> [--out FILE] [--var rain_rate|rain_zoom]"
    eprintfn "                                   [--fps N] [--width N] [--height N] [--zmax R]"
    exit 2

let store = positional.[0]
let var = opt "var" "rain_rate"
let fps = int (opt "fps" "12")
let width = int (opt "width" "960")
let height = int (opt "height" "720")
let zmax = float (opt "zmax" "50.0")
let outFile =
    match opt "out" "" with
    | "" ->
        let stem = Path.GetFileNameWithoutExtension(Path.TrimEndingDirectorySeparator store)
        Path.Combine(Path.GetDirectoryName(Path.TrimEndingDirectorySeparator store), sprintf "%s_%s.mp4" stem var)
    | p -> p

let ydim, xdim, latv, lonv =
    match var with
    | "rain_rate" -> "y", "x", "lat", "lon"
    | "rain_zoom" -> "yz", "xz", "lat_zoom", "lon_zoom"
    | other -> failwithf "--var must be rain_rate or rain_zoom (got '%s')" other

// ---- store metadata -------------------------------------------------------
// Two small reads rather than a provider load: the scan count from the array's
// zarr.json, and the clock from time_min's single chunk (little-endian f8,
// which is the only layout ZarrProvider reads back anyway).

let scanCount =
    use doc = JsonDocument.Parse(File.ReadAllText(Path.Combine(store, var, "zarr.json")))
    doc.RootElement.GetProperty("shape").[0].GetInt32()

let minutes =
    let bytes = File.ReadAllBytes(Path.Combine(store, "time_min", "c", "0"))
    Array.init (bytes.Length / 8) (fun i -> BitConverter.ToDouble(bytes, i * 8))

if minutes.Length < scanCount then
    failwithf "time_min has %d entries but %s has %d scans" minutes.Length var scanCount

printfn "%s: %d scans" var scanCount

// ---- 1. the generated program --------------------------------------------

let hhmm (x: float) = sprintf "%02d:%02d" (int x / 60) (int x % 60)
let trace = if var = "rain_rate" then "heatmap" else "contourf"
let levels = if trace = "heatmap" then "" else "20: levels, "

let program =
    let sb = StringBuilder()
    let line (s: string) = sb.Append(s).Append('\n') |> ignore
    line "// GENERATED by render_video.fsx -- one fixed-range frame per scan."
    line "import zarr as z"
    line "import plot"
    line (sprintf "let store = z.load(\"%s\")" (store.Replace("\\", "/")))
    line "type Scan = store.index.scan"
    line (sprintf "type Yv = store.index.%s" ydim)
    line (sprintf "type Xv = store.index.%s" xdim)
    line (sprintf "let R: Array<Float32 like Scan, Yv, Xv> = store.vars.%s |> z.read" var)
    line (sprintf "let ax_y: Array<Float64 like Yv> = store.vars.%s |> z.read" latv)
    line (sprintf "let ax_x: Array<Float64 like Xv> = store.vars.%s |> z.read" lonv)
    for k in 0 .. scanCount - 1 do
        // A bare curried view: partial indexing IS the frame, at Float32.
        line (sprintf "let f%d = R((%d : Scan))" k k)
        line (sprintf "let p%d = plot.%s(ax_x, ax_y, f%d, %s0.0: zmin, %g: zmax, \"%sZ  Padang rain (mm/h)\": title, \"longitude\": xlabel, \"latitude\": ylabel)"
                      k trace k levels zmax (hhmm minutes.[k]))
    sb.ToString()

let work = Path.Combine(Path.GetTempPath(), "blade-radar-video-" + string (Diagnostics.Process.GetCurrentProcess().Id))
Directory.CreateDirectory work |> ignore
let src = Path.Combine(work, "video.blade")
File.WriteAllText(src, program, ASCIIEncoding())

// ---- 2. run it, harvest the frames ---------------------------------------
// stdout is read as BYTES and split on '\n' by hand. The frame sentinel is
// \x01-delimited, so any text decoding is free to mangle it.

let runCapturingBytes (exe: string) (args: string) (extraPath: string) (stdin: byte[] option) =
    let psi = ProcessStartInfo(exe, args, WorkingDirectory = work,
                               RedirectStandardOutput = true, RedirectStandardError = true,
                               RedirectStandardInput = stdin.IsSome, UseShellExecute = false)
    if extraPath <> "" then
        psi.Environment.["PATH"] <- extraPath + string Path.PathSeparator + psi.Environment.["PATH"]
    use p = Process.Start psi
    // Both pipes are drained CONCURRENTLY with the write below: a child that
    // fills either buffer while we are blocked on the other deadlocks, and
    // this one is handed ~140 MB of specs on stdin.
    use outBuf = new MemoryStream()
    let copyOut = p.StandardOutput.BaseStream.CopyToAsync outBuf
    let readErr = p.StandardError.ReadToEndAsync()
    match stdin with
    | Some bytes ->
        p.StandardInput.BaseStream.Write(bytes, 0, bytes.Length)
        p.StandardInput.BaseStream.Flush()
        p.StandardInput.Close()
    | None -> ()
    copyOut.Wait()
    p.WaitForExit()
    p.ExitCode, outBuf.ToArray(), readErr.Result

let sw = Stopwatch.StartNew()
let code, stdoutBytes, stderrText = runCapturingBytes bladeExe (sprintf "run \"%s\"" src) msysBin None
if code <> 0 then
    eprintfn "blade run failed (exit %d):\n%s" code (stderrText.Substring(0, min 2000 stderrText.Length))
    exit 1

let frames =
    let text = Encoding.UTF8.GetString stdoutBytes
    text.Split('\n')
    |> Array.map (fun l -> l.TrimEnd('\r'))
    |> Array.filter (fun l -> l.StartsWith sentinel)
    |> Array.map (fun l -> l.Substring(sentinel.Length))
printfn "blade run: %d frames in %.1fs" frames.Length sw.Elapsed.TotalSeconds
if frames.Length <> scanCount then
    failwithf "expected %d frames, harvested %d" scanCount frames.Length

// ---- 3. one gr-render --video session ------------------------------------
// Each frame line is a display frame; the FIGURE is its "data" member, handed
// over verbatim (a reparse-and-reserialise through any number type would be
// free to move the last digit of every coordinate).

if isNull (Environment.GetEnvironmentVariable "GRDIR") then
    failwith "GRDIR is not set (gr-render needs it; see tools/gr-render/README.md)"

let payload =
    let sb = StringBuilder()
    frames |> Array.iteri (fun i line ->
        use doc = JsonDocument.Parse line
        if i > 0 then sb.Append('\n') |> ignore
        sb.Append(doc.RootElement.GetProperty("data").GetRawText()) |> ignore)
    Encoding.UTF8.GetBytes(sb.ToString())

let grBin = Path.Combine(Environment.GetEnvironmentVariable "GRDIR", "bin")
sw.Restart()
let vcode, _, vstderr =
    runCapturingBytes grRender
        (sprintf "--video --out \"%s\" --width %d --height %d --fps %d" outFile width height fps)
        grBin (Some payload)
if vcode <> 0 then
    eprintfn "gr-render failed:\n%s" (vstderr.Substring(0, min 2000 vstderr.Length))
    exit 1
printfn "gr-render: %s in %.1fs" (vstderr.Trim()) sw.Elapsed.TotalSeconds

try Directory.Delete(work, true) with _ -> ()
