(* ===================================================================== *)
(* BladeTrinityAsym.v -- Layer 3d: THE TRINITY IS NOT CO-EQUAL.          *)
(*                                                                       *)
(* Thesis (mechanized here): loop reification (LR) and dimensional       *)
(* currying (DC) are GENERATORS; arity polymorphism (AP) is the FORCED   *)
(* CLOSURE of LR under the applicative monoid, typeable by reusing DC's  *)
(* dependent-typing resource.  The dependency structure is a DAG, not a  *)
(* triangle of co-equals.  Witness for {LR, DC} without AP: the unary    *)
(* C++ object_for prototype (a reified loop over a curried array, fixed  *)
(* arity) -- semantically the one-arrow instance of this file's          *)
(* generators.                                                           *)
(*                                                                       *)
(*   sprod + unit/assoc laws     the applicative monoid <*> on           *)
(*                               (semantic) plans, with its laws          *)
(*                               CHECKED (formalism section 12 asserts   *)
(*                               them)                                   *)
(*   enumShape_cons              the n-ary enumerator consumes one       *)
(*                               reified arrow at a time via <*>          *)
(*   ap_semantics_is_free_fold   AP-EMERGENCE: the arbitrary-arity      *)
(*                               enumerator IS the free fold of the      *)
(*                               binary combinator over reified arrows   *)
(*                               -- a single non-arity-indexed function; *)
(*                               arity is just list length               *)
(*   nary_generated_by_unary     every n-ary loop is generated by UNARY *)
(*                               loops under <*> -- the formal echo of   *)
(*                               the unary object_for prototype          *)
(*   enumShape_monoid_hom        EVALUATION IS STRICTLY MONOIDAL:        *)
(*                               enumShape (s1 ++ s2) = sprod of the     *)
(*                               evaluations, as list EQUALITY.  This is *)
(*                               the checkable fragment of the V -| P    *)
(*                               discussion: V (evaluation) is a strict  *)
(*                               monoidal functor from plans to values.  *)
(*                               The adjunction itself remains           *)
(*                               conjectural (no Hom-sets yet); its      *)
(*                               unit is `compute`/materialization, and  *)
(*                               non-faithfulness of V (12.7) is the     *)
(*                               optimization space.                     *)
(*                                                                       *)
(* What is NOT emergent about AP: typing the closure.  The output type   *)
(* family must be term-indexed by arity (output_family_not_constant,     *)
(* BladeTrinity) -- but that is the SAME resource DC already requires    *)
(* at arity 1 (residual_not_constant, BladeDMWF), reused with a          *)
(* different index.  AP introduces no new type-theoretic resource.       *)
(*                                                                       *)
(* Imports BladeDMWF, BladeArrow (flat_map_ext), BladeTrinity.           *)
(* Coq 8.18, stdlib only.                                                *)
(* ===================================================================== *)

From Blade Require Import BladeDMWF BladeArrow BladeTrinity.
Require Import List Arith Lia Setoid.
Import ListNotations.

(* ---------------- list plumbing ---------------- *)

Lemma fm_app : forall (A B : Type) (f : A -> list B) (l1 l2 : list A),
  flat_map f (l1 ++ l2) = flat_map f l1 ++ flat_map f l2.
Proof.
  induction l1 as [|a l1 IH]; intros; simpl; [reflexivity |].
  rewrite IH, app_assoc. reflexivity.
Qed.

Lemma flat_map_map : forall (A B C : Type) (f : A -> B) (g : B -> list C) l,
  flat_map g (map f l) = flat_map (fun x => g (f x)) l.
Proof.
  induction l as [|a l IH]; simpl; [reflexivity | rewrite IH; reflexivity].
Qed.

Lemma map_flat_map : forall (A B C : Type) (f : A -> list B) (g : B -> C) l,
  map g (flat_map f l) = flat_map (fun x => map g (f x)) l.
Proof.
  induction l as [|a l IH]; simpl; [reflexivity |].
  rewrite map_app, IH. reflexivity.
Qed.

Lemma flat_map_flat_map :
  forall (A B C : Type) (f : A -> list B) (g : B -> list C) l,
  flat_map g (flat_map f l) = flat_map (fun x => flat_map g (f x)) l.
Proof.
  induction l as [|a l IH]; simpl; [reflexivity |].
  rewrite fm_app, IH. reflexivity.
Qed.

Lemma concat_map_singleton : forall (A : Type) (s : list A),
  concat (map (fun c => [c]) s) = s.
Proof.
  induction s as [|a s IH]; simpl; [reflexivity | rewrite IH; reflexivity].
Qed.

Lemma Forall2_map_l :
  forall (A B C : Type) (f : A -> B) (P : B -> C -> Prop) (l : list A) (l' : list C),
  Forall2 P (map f l) l' <-> Forall2 (fun x y => P (f x) y) l l'.
Proof.
  intros A B C f P l. induction l as [|a l IH]; intros l'; simpl;
    split; intro H.
  - inversion H. constructor.
  - inversion H. constructor.
  - inversion H as [| x y lx ly Hp Hf]; subst.
    constructor; [exact Hp | apply IH; exact Hf].
  - inversion H as [| x y lx ly Hp Hf]; subst.
    constructor; [exact Hp | apply IH; exact Hf].
Qed.

(* ---------------- the applicative monoid on semantic plans ----------- *)

(* sprod is <*> on evaluated plans: pairwise concatenation of tuples.    *)
Definition sprod (l1 l2 : list (list nat)) : list (list nat) :=
  flat_map (fun t => map (app t) l2) l1.

Lemma sprod_unit_l : forall l, sprod [ [] ] l = l.
Proof.
  intro l. unfold sprod. simpl. rewrite app_nil_r.
  induction l as [|x l IH]; simpl; [reflexivity |].
  rewrite IH. reflexivity.
Qed.

Lemma sprod_cons : forall x l1 l2,
  sprod (x :: l1) l2 = map (app x) l2 ++ sprod l1 l2.
Proof. reflexivity. Qed.

Lemma sprod_unit_r : forall l, sprod l [ [] ] = l.
Proof.
  induction l as [|x l IH]; [reflexivity |].
  rewrite sprod_cons, IH. simpl. rewrite app_nil_r. reflexivity.
Qed.

Lemma sprod_assoc : forall a b c,
  sprod (sprod a b) c = sprod a (sprod b c).
Proof.
  intros a b c. unfold sprod.
  rewrite flat_map_flat_map.
  apply flat_map_ext. intro t.
  rewrite flat_map_map, map_flat_map.
  apply flat_map_ext. intro x.
  rewrite map_map.
  apply map_ext. intro y. symmetry. apply app_assoc.
Qed.

(* ---------------- AP-emergence ---------------- *)

(* The n-ary enumerator consumes one reified arrow at a time via <*>.   *)
Lemma enumShape_cons : forall c s,
  enumShape (c :: s) = sprod (enumIx c) (enumShape s).
Proof. reflexivity. Qed.

(* THE EMERGENCE THEOREM: the arbitrary-arity enumerator is the free    *)
(* fold of the binary combinator over the list of reified arrows.       *)
(* enumShape is ONE function; nothing in it is indexed by arity --      *)
(* arity is the length of a runtime list of values.  Semantically, AP   *)
(* is a THEOREM about {LR, DC}, not an axiom beside them.               *)
Theorem ap_semantics_is_free_fold : forall s : Shape,
  enumShape s
  = fold_right (fun c acc => sprod (enumIx c) acc) [ [] ] s.
Proof.
  induction s as [|c s IH]; simpl; [reflexivity |].
  rewrite <- IH. apply enumShape_cons.
Qed.

(* Every n-ary loop is generated by UNARY loops under <*>: the direct   *)
(* formalization of the unary object_for prototype generates the        *)
(* language (via BladeCurrying.enumShape_single, In p (enumShape [c])  *)
(* is exactly membership in the one-arrow loop).                        *)
Theorem nary_generated_by_unary : forall (s : Shape) (t : list nat),
  In t (enumShape s) <->
  exists parts : list (list nat),
    t = concat parts /\
    length parts = length s /\
    Forall2 (fun c p => In p (enumShape [c])) s parts.
Proof.
  intros s t.
  rewrite <- (concat_map_singleton _ s) at 1.
  rewrite trinity_fold_closure.
  split; intros (parts & Et & Hlen & HF); exists parts.
  - rewrite map_length in Hlen.
    split; [exact Et | split; [exact Hlen |]].
    exact (proj1 (Forall2_map_l IxRec Shape (list nat)
                    (fun c => [c]) (fun sh p => In p (enumShape sh))
                    s parts) HF).
  - split; [exact Et | split].
    + rewrite map_length. exact Hlen.
    + exact (proj2 (Forall2_map_l IxRec Shape (list nat)
                      (fun c => [c]) (fun sh p => In p (enumShape sh))
                      s parts) HF).
Qed.

(* ---------------- monoidal evaluation (the V -| P fragment) ---------- *)

(* EVALUATION IS A STRICT MONOID HOMOMORPHISM from (Shape, ++, []) to   *)
(* (semantic plans, sprod, [[]]): list equality, not mere membership    *)
(* equivalence.  Categorically: V is a strict monoidal functor.  This   *)
(* is the checked core of the V -| P story; together with               *)
(* ap_semantics_is_free_fold it says the closure that AP names is the   *)
(* image under V of the free monoid on reified arrows.                  *)
Theorem enumShape_monoid_hom : forall s1 s2 : Shape,
  enumShape (s1 ++ s2) = sprod (enumShape s1) (enumShape s2).
Proof.
  induction s1 as [|c s1 IH]; intros s2.
  - symmetry. apply sprod_unit_l.
  - change ((c :: s1) ++ s2) with (c :: (s1 ++ s2)).
    rewrite !enumShape_cons, IH.
    symmetry. apply sprod_assoc.
Qed.

(* ===================================================================== *)
(* Ledger for the formalism rewrite:                                     *)
(*  - Theorem 9.7 should be restated: {LR, DC} generate; AP is the       *)
(*    canonical closure, forced by the design goal (typed n-ary          *)
(*    symmetric iteration), reusing DC's term-indexed families with      *)
(*    arity as the index.  "Inseparable" survives as mutual PRESENCE     *)
(*    under the goal; co-equality does not.                              *)
(*  - Section 12's monoid/applicative laws for <*> are now checked at   *)
(*    the semantic level (sprod_unit_l/r, sprod_assoc,                   *)
(*    enumShape_monoid_hom).                                             *)
(*  - Sections 12.5-12.8 (V -| P) should present: monoidality of         *)
(*    evaluation (checked, above); unit = compute/materialization;       *)
(*    non-faithfulness of V = the optimization space (12.7, keep);       *)
(*    the adjunction proper as conjecture pending a refinement-morphism  *)
(*    definition for Plan's Hom-sets (or demote to a Galois              *)
(*    connection).                                                       *)
(* ===================================================================== *)
