(* ===================================================================== *)
(* BladeDeduceExact.v -- WHAT SYMMETRY DEDUCTION IS EXACT FOR            *)
(* (docs/plans/plan-uniform-optimality.md, T4; implementation            *)
(* src/Deduce.fs).                                                       *)
(*                                                                       *)
(* BladeDeduce proves every rule that ever ANSWERS sound.  This file     *)
(* asks the converse: when the deduction says nothing, was there really  *)
(* nothing to say?  It answers in BladeOrbitWork's term model, where a   *)
(* kernel body is a term over its parameters and the operator symbols    *)
(* are uninterpreted up to a declared commutativity.                     *)
(*                                                                       *)
(*   uniform_equality_exact   two bodies agree under EVERY               *)
(*                            interpretation respecting the declared     *)
(*                            laws, on all data, iff they are equal      *)
(*                            modulo those laws (teq).  Soundness is an  *)
(*                            induction; completeness is the free model, *)
(*                            which is faithful (free_faithful).         *)
(*   uniform_symmetry_is_     so the uniform symmetry group of a body is *)
(*     automorphism           its syntactic automorphism group modulo    *)
(*                            the laws, and membership is decidable by a *)
(*                            structural walk (teqb).                    *)
(*   mirror_spec              src/Deduce.fs's mirrorEq, modelled node    *)
(*                            for node, IS that walk composed with the   *)
(*                            swap: mirror i j l r = teqb (swap l) r.    *)
(*   parfix_exact             the deduction rule answers PInv on a       *)
(*                            transposition EXACTLY when that            *)
(*                            transposition is a uniform symmetry.       *)
(*   deduced_group_sound,     the group the compiler grants is the one   *)
(*   deduced_is_maximal,      GENERATED by the adjacent transpositions   *)
(*   deduced_group_largest    it certifies; it is sound, and it contains *)
(*                            every group generated by adjacent          *)
(*                            transpositions inside the symmetry group   *)
(*                            -- the largest contiguous-block Young      *)
(*                            subgroup.                                  *)
(*   young_generated          such a subgroup IS generated by its        *)
(*                            interior adjacent transpositions, in the   *)
(*                            tower's list semantics: BladeDeduce's      *)
(*                            adjacent_transpositions_generate, from one *)
(*                            block to a shape.                          *)
(*                                                                       *)
(* THE FINDING.  par models the rule in the order it shipped until       *)
(* 2026-09-19: mirror first, and a mirror hit answered from the op's     *)
(* swap class alone.  Under a non-commuting op that class is "no claim", *)
(* and the rule stopped there without looking at the operands.           *)
(*                                                                       *)
(*   par_sound, par_le_parfix the old order was sound and below the      *)
(*                            exact rule;                                *)
(*   shipped_rule_incomplete  (x + y) / (y + x) is a uniform symmetry    *)
(*                            the old order missed.                      *)
(*                                                                       *)
(* The compiler confirmed it (no BL4010 on that body, and a false        *)
(* `anticomm` pin on it accepted where BL4013 should refuse), parityOf   *)
(* now falls through to the chain rule, and tests/corpus/symmetry/049-   *)
(* 051 pin the three behaviours.  parfix is the rule as it now stands.   *)
(*                                                                       *)
(* WHAT STAYS OUT OF REACH, each a closed witness:                       *)
(*                                                                       *)
(*   nonadjacent_symmetry_    g(h(a, c), b): the transposition (0 2) is  *)
(*     missed                 a symmetry, no adjacent one is.  Reachable *)
(*                            only by reordering the parameters.         *)
(*   wreath_symmetry_missed   g(h(a, b), h(c, d)): the deduced group is  *)
(*                            S_2 x S_2, the symmetry group contains the *)
(*                            block swap too -- BladeWreath's wreath     *)
(*                            product, of order 8.                       *)
(*                                                                       *)
(* Both are consequences of the design, not defects: n - 1 adjacent      *)
(* checks buy exactly the contiguous-block Young subgroups, and the      *)
(* theorems above say the deduction gets ALL of those.                   *)
(*                                                                       *)
(* Scope.  The UNSIGNED fragment: variables, unary and binary operator   *)
(* symbols, commutativity as the only law.  PNeg (the sign chain rule),  *)
(* PConj, call summaries, reduce, if/match and let-flattening are not    *)
(* modelled; BladeDeduce covers their soundness and nothing here speaks  *)
(* to their completeness.  Associativity is deliberately NOT a law: it   *)
(* is not licensed for floating point, and the free model agrees.        *)
(*                                                                       *)
(* Imports BladeOptimal, BladeOrbitWork.  Coq 8.18, stdlib only.         *)
(* ===================================================================== *)

From Blade Require Import BladeOptimal BladeOrbitWork.
Require Import List Arith Lia Bool Permutation.
Import ListNotations.

(* ===================================================================== *)
(* RENAMING.  A kernel body is a term whose leaves are its parameters    *)
(* (and captures); a permutation of the parameters acts by renaming.     *)
(* Everything is stated up to POINTWISE equality of renamings, so no     *)
(* functional extensionality is needed anywhere.                         *)
(* ===================================================================== *)

Fixpoint ren (rho : nat -> nat) (t : tm) : tm :=
  match t with
  | Leaf i => Leaf (rho i)
  | App1 s t1 => App1 s (ren rho t1)
  | App2 s t1 t2 => App2 s (ren rho t1) (ren rho t2)
  end.

Lemma ren_ext : forall rho rho' t,
  (forall x, rho x = rho' x) -> ren rho t = ren rho' t.
Proof.
  intros rho rho' t H. induction t as [i | s t1 IH1 | s t1 IH1 t2 IH2]; simpl.
  - rewrite H. reflexivity.
  - rewrite IH1. reflexivity.
  - rewrite IH1, IH2. reflexivity.
Qed.

Lemma ren_ren : forall rho sigma t,
  ren rho (ren sigma t) = ren (fun x => rho (sigma x)) t.
Proof.
  intros rho sigma t. induction t as [i | s t1 IH1 | s t1 IH1 t2 IH2]; simpl.
  - reflexivity.
  - rewrite IH1. reflexivity.
  - rewrite IH1, IH2. reflexivity.
Qed.

Lemma ren_id : forall rho t, (forall x, rho x = x) -> ren rho t = t.
Proof.
  intros rho t H. induction t as [i | s t1 IH1 | s t1 IH1 t2 IH2]; simpl.
  - rewrite H. reflexivity.
  - rewrite IH1. reflexivity.
  - rewrite IH1, IH2. reflexivity.
Qed.

Lemma eval_ren : forall leaf k rho t,
  eval leaf k (ren rho t) = eval (fun i => leaf (rho i)) k t.
Proof.
  intros leaf k rho t. induction t as [i | s t1 IH1 | s t1 IH1 t2 IH2];
    cbn [ren eval].
  - reflexivity.
  - rewrite IH1. reflexivity.
  - rewrite IH1, IH2. reflexivity.
Qed.

(* the transposition of two parameters *)
Definition sw (i j x : nat) : nat :=
  if x =? i then j else if x =? j then i else x.

Lemma sw_invol : forall i j x, sw i j (sw i j x) = x.
Proof.
  intros i j x. unfold sw.
  destruct (Nat.eqb_spec x i) as [-> | Hxi].
  - destruct (Nat.eqb_spec j i) as [-> | Hji]; [reflexivity |].
    rewrite Nat.eqb_refl. reflexivity.
  - destruct (Nat.eqb_spec x j) as [-> | Hxj].
    + rewrite Nat.eqb_refl. reflexivity.
    + destruct (Nat.eqb_spec x i); [contradiction |].
      destruct (Nat.eqb_spec x j); [contradiction | reflexivity].
Qed.

Lemma ren_sw_invol : forall i j t, ren (sw i j) (ren (sw i j) t) = t.
Proof.
  intros i j t. rewrite ren_ren. apply ren_id. apply sw_invol.
Qed.

Section DeduceExact.
  Variable comm : nat -> bool.

  (* =================================================================== *)
  (* PART A.  SYNTACTIC EQUALITY MODULO THE DECLARED LAWS, and its       *)
  (* exactness: two kernel bodies agree under EVERY interpretation of    *)
  (* the operator symbols that respects the declared commutativity, on   *)
  (* all data, iff they are equal modulo that commutativity.  Soundness  *)
  (* is an induction; completeness is BladeOrbitWork's free model, in    *)
  (* which a value is the name of a term class.                          *)
  (* =================================================================== *)
  Inductive teq : tm -> tm -> Prop :=
  | teq_leaf : forall i, teq (Leaf i) (Leaf i)
  | teq_1 : forall s a a', teq a a' -> teq (App1 s a) (App1 s a')
  | teq_2 : forall s a a' b b',
      teq a a' -> teq b b' -> teq (App2 s a b) (App2 s a' b')
  | teq_2c : forall s a a' b b', comm s = true ->
      teq a b' -> teq b a' -> teq (App2 s a b) (App2 s a' b').

  Lemma teq_leaf_inv : forall a b, teq (Leaf a) (Leaf b) -> a = b.
  Proof. intros a b H. inversion H. reflexivity. Qed.

  Lemma teq_refl : forall t, teq t t.
  Proof.
    induction t; [apply teq_leaf | apply teq_1 | apply teq_2]; assumption.
  Qed.

  Lemma teq_sym : forall a b, teq a b -> teq b a.
  Proof.
    intros a b H. induction H.
    - apply teq_leaf.
    - apply teq_1. assumption.
    - apply teq_2; assumption.
    - apply teq_2c; assumption.
  Qed.

  Lemma teq_ren : forall rho a b, teq a b -> teq (ren rho a) (ren rho b).
  Proof.
    intros rho a b H. induction H; cbn [ren].
    - apply teq_leaf.
    - apply teq_1. assumption.
    - apply teq_2; assumption.
    - apply teq_2c; assumption.
  Qed.

  Lemma teq_sound : forall a b, teq a b ->
    forall leaf k, Kc comm k -> eval leaf k a = eval leaf k b.
  Proof.
    intros a b H leaf k Hk. induction H; cbn [eval].
    - reflexivity.
    - rewrite IHteq. reflexivity.
    - rewrite IHteq1, IHteq2. reflexivity.
    - rewrite IHteq1, IHteq2. apply Hk. assumption.
  Qed.

  (* equal canonical binary queries: same symbol, and the arguments      *)
  (* agree directly or -- only under a declaration -- crossed            *)
  Lemma cq_Q2_inv : forall s a b s' a' b',
    cq comm (Q2 s a b) = cq comm (Q2 s' a' b') ->
    s = s' /\ ((a = a' /\ b = b') \/ (comm s = true /\ a = b' /\ b = a')).
  Proof.
    intros s a b s' a' b' E. unfold cq in E.
    destruct (comm s) eqn:Cs; destruct (comm s') eqn:Cs';
      repeat match type of E with
             | context [?x <=? ?y] => destruct (x <=? y)
             end;
      injection E as E1 E2 E3; subst;
      (split; [reflexivity |]);
      first [ left; split; reflexivity
            | right; repeat split; congruence ].
  Qed.

  (* THE FREE MODEL IS FAITHFUL. *)
  Lemma free_faithful : forall a b,
    eval cleaf (kfree comm chash) a = eval cleaf (kfree comm chash) b ->
    teq a b.
  Proof.
    induction a as [i | s a1 IH1 | s a1 IH1 a2 IH2];
      intros [j | s' b1 | s' b1 b2] E; cbn [eval] in E; unfold kfree in E.
    - unfold cleaf in E. assert (i = j) by lia. subst. apply teq_leaf.
    - exfalso. exact (chash_cleaf _ _ (eq_sym E)).
    - exfalso. exact (chash_cleaf _ _ (eq_sym E)).
    - exfalso. exact (chash_cleaf _ _ E).
    - apply chash_inj in E. cbn [cq] in E. injection E as Es Ev. subst s'.
      apply teq_1. apply IH1. exact Ev.
    - apply chash_inj in E. symmetry in E.
      exfalso. exact (cq_Q2_not_Q1 comm _ _ _ _ _ E).
    - exfalso. exact (chash_cleaf _ _ E).
    - apply chash_inj in E.
      exfalso. exact (cq_Q2_not_Q1 comm _ _ _ _ _ E).
    - apply chash_inj in E. apply cq_Q2_inv in E as [Es [[E1 E2] | [Hc [E1 E2]]]];
        subst s'.
      + apply teq_2; [apply IH1 | apply IH2]; assumption.
      + apply teq_2c; [exact Hc | apply IH1 | apply IH2]; assumption.
  Qed.

  (* T4, first clause: uniform (all-interpretation, all-data) equality   *)
  (* of kernel bodies IS syntactic equality modulo the declared laws.    *)
  Theorem uniform_equality_exact : forall a b,
    (forall leaf k, Kc comm k -> eval leaf k a = eval leaf k b) <-> teq a b.
  Proof.
    intros a b. split.
    - intro H. apply free_faithful. apply H. apply kfree_Kc.
    - intros H leaf k Hk. exact (teq_sound a b H leaf k Hk).
  Qed.

  (* transitivity for free: it is transitivity of equality in the models *)
  Corollary teq_trans : forall a b c, teq a b -> teq b c -> teq a c.
  Proof.
    intros a b c Hab Hbc. apply uniform_equality_exact. intros leaf k Hk.
    rewrite (teq_sound a b Hab leaf k Hk). exact (teq_sound b c Hbc leaf k Hk).
  Qed.

  (* ... and it is decidable, by structural comparison *)
  Fixpoint teqb (a b : tm) : bool :=
    match a, b with
    | Leaf i, Leaf j => i =? j
    | App1 s a1, App1 s' b1 => (s =? s') && teqb a1 b1
    | App2 s a1 a2, App2 s' b1 b2 =>
        (s =? s') && ((teqb a1 b1 && teqb a2 b2)
                      || (comm s && teqb a1 b2 && teqb a2 b1))
    | _, _ => false
    end.

  Lemma teqb_spec : forall a b, teqb a b = true <-> teq a b.
  Proof.
    induction a as [i | s a1 IH1 | s a1 IH1 a2 IH2];
      intros [j | s' b1 | s' b1 b2]; cbn [teqb];
      try (split; [discriminate | intro H; inversion H]).
    - rewrite Nat.eqb_eq. split; [intros ->; apply teq_leaf |].
      intro H. inversion H. reflexivity.
    - rewrite andb_true_iff, Nat.eqb_eq, IH1. split.
      + intros [-> H]. apply teq_1. exact H.
      + intro H. inversion H; subst. split; [reflexivity | assumption].
    - rewrite andb_true_iff, orb_true_iff, !andb_true_iff, Nat.eqb_eq.
      rewrite (IH1 b1), (IH2 b2), (IH1 b2), (IH2 b1). split.
      + intros [-> [[H1 H2] | [[Hc H1] H2]]];
          [apply teq_2 | apply teq_2c]; assumption.
      + intro H. inversion H; subst; (split; [reflexivity |]);
          [left | right]; repeat split; assumption.
  Qed.

  (* THE UNIFORM SYMMETRY GROUP of a kernel body: the renamings no       *)
  (* interpretation can detect.  By the above it is the body's syntactic *)
  (* automorphism group modulo the laws, and membership is decidable.    *)
  Definition usym (rho : nat -> nat) (t : tm) : Prop :=
    forall leaf k, Kc comm k -> eval leaf k (ren rho t) = eval leaf k t.

  Theorem uniform_symmetry_is_automorphism : forall rho t,
    usym rho t <-> teqb (ren rho t) t = true.
  Proof.
    intros rho t. unfold usym.
    rewrite teqb_spec. apply uniform_equality_exact.
  Qed.

  Lemma usym_compose : forall rho sigma t,
    usym rho t -> usym sigma t -> usym (fun x => rho (sigma x)) t.
  Proof.
    intros rho sigma t Hr Hs leaf k Hk.
    rewrite <- ren_ren. rewrite eval_ren.
    rewrite (Hs (fun i => leaf (rho i)) k Hk).
    rewrite <- eval_ren. exact (Hr leaf k Hk).
  Qed.

  (* =================================================================== *)
  (* PART B.  THE DEDUCTION, modelled on src/Deduce.fs at the unsigned   *)
  (* fragment: mirror is mirrorEq (a simultaneous walk, cross-matching   *)
  (* the swapped pair at the leaves and the operands of a commutative    *)
  (* op); par is parityOf's Var / UnaryOp / BinOp arms in the order they *)
  (* shipped until 2026-09-19 -- mirror first, a mirror hit answering    *)
  (* from the op's swap class alone -- and parfix is the rule as it now  *)
  (* stands.                                                             *)
  (* =================================================================== *)
  Inductive parity : Type := PInv | PBottom.

  Fixpoint mirror (i j : nat) (l r : tm) : bool :=
    match l, r with
    | Leaf a, Leaf b =>
        ((a =? i) && (b =? j)) || ((a =? j) && (b =? i))
        || ((a =? b) && negb (a =? i) && negb (a =? j))
    | App1 s l1, App1 s' r1 => (s =? s') && mirror i j l1 r1
    | App2 s l1 l2, App2 s' r1 r2 =>
        (s =? s') && ((mirror i j l1 r1 && mirror i j l2 r2)
                      || (comm s && mirror i j l1 r2 && mirror i j l2 r1))
    | _, _ => false
    end.

  (* mirrorEq is "the swap of l equals r, modulo the laws" *)
  Lemma mirror_spec : forall i j, i <> j ->
    forall l r, mirror i j l r = teqb (ren (sw i j) l) r.
  Proof.
    intros i j Hij. induction l as [a | s l1 IH1 | s l1 IH1 l2 IH2];
      intros [b | s' r1 | s' r1 r2]; cbn [mirror ren teqb]; try reflexivity.
    - unfold sw.
      destruct (Nat.eqb_spec a i), (Nat.eqb_spec a j); subst; try lia; simpl;
        repeat match goal with
               | |- context [?x =? ?y] => destruct (Nat.eqb_spec x y)
               end; subst; try reflexivity; try lia.
    - rewrite IH1. reflexivity.
    - rewrite IH1, IH2, (IH1 r2), (IH2 r1). reflexivity.
  Qed.

  Definition both (p q : parity) : parity :=
    match p, q with PInv, PInv => PInv | _, _ => PBottom end.

  (* as shipped until 2026-09-19 *)
  Fixpoint par (i j : nat) (e : tm) : parity :=
    match e with
    | Leaf a => if (a =? i) || (a =? j) then PBottom else PInv
    | App1 _ e1 => par i j e1
    | App2 s l r =>
        if mirror i j l r
        then (if comm s then PInv else PBottom)
        else both (par i j l) (par i j r)
    end.

  (* as it now stands: the mirror rule fires only when it can answer *)
  Fixpoint parfix (i j : nat) (e : tm) : parity :=
    match e with
    | Leaf a => if (a =? i) || (a =? j) then PBottom else PInv
    | App1 _ e1 => parfix i j e1
    | App2 s l r =>
        if mirror i j l r && comm s
        then PInv
        else both (parfix i j l) (parfix i j r)
    end.

  (* T4, second clause: the rule is EXACT for every adjacent (indeed     *)
  (* every) transposition -- it answers PInv precisely on the uniform    *)
  (* symmetries.                                                         *)
  Lemma parfix_teq : forall i j, i <> j -> forall e,
    parfix i j e = PInv <-> teq (ren (sw i j) e) e.
  Proof.
    intros i j Hij. induction e as [a | s e1 IH1 | s l IHl r IHr];
      cbn [parfix ren].
    - unfold sw. split.
      + destruct (Nat.eqb_spec a i), (Nat.eqb_spec a j); simpl;
          try discriminate. intros _. apply teq_leaf.
      + intro H. apply teq_leaf_inv in H.
        destruct (Nat.eqb_spec a i), (Nat.eqb_spec a j); simpl in *;
          subst; try reflexivity; lia.
    - rewrite IH1. split; intro H.
      + apply teq_1. exact H.
      + inversion H; subst. assumption.
    - split.
      + destruct (mirror i j l r && comm s) eqn:M.
        * intros _. apply andb_true_iff in M as [Hm Hc].
          rewrite (mirror_spec i j Hij) in Hm. apply teqb_spec in Hm.
          apply teq_2c; [exact Hc | exact Hm |].
          apply teq_sym. apply (teq_ren (sw i j)) in Hm.
          rewrite ren_sw_invol in Hm. exact Hm.
        * destruct (parfix i j l) eqn:Pl, (parfix i j r) eqn:Pr;
            simpl; try discriminate.
          intros _. apply teq_2; [apply IHl | apply IHr]; reflexivity.
      + intro H. inversion H; subst.
        * destruct (mirror i j l r && comm s); [reflexivity |].
          rewrite (proj2 IHl), (proj2 IHr) by assumption. reflexivity.
        * assert (Hm : mirror i j l r = true).
          { rewrite (mirror_spec i j Hij). apply teqb_spec. assumption. }
          rewrite Hm. match goal with Hc : comm s = true |- _ => rewrite Hc end.
          reflexivity.
  Qed.

  Theorem parfix_exact : forall i j, i <> j -> forall e,
    parfix i j e = PInv <-> usym (sw i j) e.
  Proof.
    intros i j Hij e. rewrite (parfix_teq i j Hij). unfold usym.
    symmetry. apply uniform_equality_exact.
  Qed.

  (* the old order is below it, hence was SOUND ... *)
  Lemma par_le_parfix : forall i j e, par i j e = PInv -> parfix i j e = PInv.
  Proof.
    intros i j. induction e as [a | s e1 IH1 | s l IHl r IHr];
      cbn [par parfix]; intro H.
    - exact H.
    - apply IH1. exact H.
    - destruct (mirror i j l r) eqn:M; simpl.
      + destruct (comm s); [reflexivity | discriminate].
      + destruct (par i j l) eqn:Pl, (par i j r) eqn:Pr; simpl in H;
          try discriminate.
        rewrite (IHl eq_refl), (IHr eq_refl). reflexivity.
  Qed.

  Theorem par_sound : forall i j, i <> j -> forall e,
    par i j e = PInv -> usym (sw i j) e.
  Proof.
    intros i j Hij e H. apply (parfix_exact i j Hij).
    apply par_le_parfix. exact H.
  Qed.

  (* =================================================================== *)
  (* PART C.  WHAT ADJACENT-PAIR DEDUCTION IS COMPLETE FOR.              *)
  (* The group it grants is the one GENERATED by the adjacent            *)
  (* transpositions it certifies.  That group is sound, and it is the    *)
  (* largest group generated by adjacent transpositions inside the       *)
  (* uniform symmetry group -- i.e. the largest contiguous-block Young   *)
  (* subgroup.  Nothing outside that shape is reachable, by design.      *)
  (* =================================================================== *)
  Inductive gen (P : nat -> Prop) : (nat -> nat) -> Prop :=
  | gen_id : forall rho, (forall x, rho x = x) -> gen P rho
  | gen_step : forall i rho rho', P i -> gen P rho ->
      (forall x, rho' x = rho (sw i (S i) x)) -> gen P rho'.

  Definition deduced (t : tm) (i : nat) : Prop := parfix i (S i) t = PInv.

  Theorem deduced_group_sound : forall t rho, gen (deduced t) rho -> usym rho t.
  Proof.
    intros t rho H. induction H as [rho Hid | i rho rho' Hi _ IH Hrho].
    - intros leaf k _. rewrite (ren_id rho t Hid). reflexivity.
    - intros leaf k Hk.
      rewrite (ren_ext rho' (fun x => rho (sw i (S i) x)) t Hrho).
      rewrite <- ren_ren. rewrite eval_ren.
      assert (Hi' : usym (sw i (S i)) t)
        by (apply parfix_exact; [lia | exact Hi]).
      rewrite (Hi' (fun x => leaf (rho x)) k Hk).
      rewrite <- eval_ren. exact (IH leaf k Hk).
  Qed.

  Theorem deduced_is_maximal : forall t i,
    usym (sw i (S i)) t -> deduced t i.
  Proof. intros t i H. apply parfix_exact; [lia | exact H]. Qed.

  Lemma gen_mono : forall (P Q : nat -> Prop),
    (forall i, P i -> Q i) -> forall rho, gen P rho -> gen Q rho.
  Proof.
    intros P Q HPQ rho H. induction H as [rho Hid | i rho rho' Hi _ IH Hrho].
    - apply gen_id. exact Hid.
    - apply (gen_step Q i rho rho'); [apply HPQ; exact Hi | exact IH | exact Hrho].
  Qed.

  (* any group generated by adjacent transpositions that are uniform     *)
  (* symmetries sits inside the deduced one                              *)
  Corollary deduced_group_largest : forall t (Q : nat -> Prop),
    (forall i, Q i -> usym (sw i (S i)) t) ->
    forall rho, gen Q rho -> gen (deduced t) rho.
  Proof.
    intros t Q HQ. apply gen_mono. intros i Hi.
    apply deduced_is_maximal. apply HQ. exact Hi.
  Qed.
End DeduceExact.

(* ===================================================================== *)
(* PART D.  THE GAPS, each a closed witness.  Symbol 0 is declared       *)
(* commutative, symbol 1 is not ("+" and "/").                           *)
(* ===================================================================== *)

Definition comm01 (s : nat) : bool := s =? 0.

(* GAP 1 (closed 2026-09-19) -- a precision bug in the old order.        *)
(* (x + y) / (y + x): the two operands mirror each other, the op does    *)
(* not commute, and the old rule answered PBottom from the mirror hit    *)
(* without looking at the operands -- each invariant on its own.         *)
Definition gap_body : tm :=
  App2 1 (App2 0 (Leaf 0) (Leaf 1)) (App2 0 (Leaf 1) (Leaf 0)).

Example shipped_rule_misses :
  par comm01 0 1 gap_body = PBottom /\
  parfix comm01 0 1 gap_body = PInv.
Proof. vm_compute. split; reflexivity. Qed.

Theorem shipped_rule_incomplete :
  usym comm01 (sw 0 1) gap_body /\ par comm01 0 1 gap_body <> PInv.
Proof.
  split.
  - apply parfix_exact; [lia | reflexivity].
  - vm_compute. discriminate.
Qed.

(* GAP 2 -- a symmetry that is not a product of ADJACENT ones.           *)
(* g(h(a, c), b), h commutative: the transposition (0 2) is a uniform    *)
(* symmetry, neither adjacent transposition is, so the deduced group is  *)
(* trivial.  Reachable only by reordering the parameters.                *)
Definition skip_body : tm := App2 1 (App2 0 (Leaf 0) (Leaf 2)) (Leaf 1).

Theorem nonadjacent_symmetry_missed :
  usym comm01 (sw 0 2) skip_body /\
  ~ deduced comm01 skip_body 0 /\ ~ deduced comm01 skip_body 1.
Proof.
  split; [| split].
  - apply uniform_symmetry_is_automorphism. reflexivity.
  - unfold deduced. vm_compute. discriminate.
  - unfold deduced. vm_compute. discriminate.
Qed.

(* GAP 3 -- a symmetry group that is not Young.  g(h(a, b), h(c, d)),    *)
(* both commutative: the deduced group is S_2 x S_2 (order 4), but the   *)
(* block swap (0 2)(1 3) is a uniform symmetry too -- the wreath product *)
(* of order 8 that BladeWreath proves sound on the input side.           *)
Definition wreath_body : tm :=
  App2 0 (App2 0 (Leaf 0) (Leaf 1)) (App2 0 (Leaf 2) (Leaf 3)).

Definition block_swap (x : nat) : nat :=
  match x with 0 => 2 | 1 => 3 | 2 => 0 | 3 => 1 | _ => x end.

Theorem wreath_symmetry_missed :
  deduced comm01 wreath_body 0 /\ deduced comm01 wreath_body 2 /\
  ~ deduced comm01 wreath_body 1 /\
  usym comm01 block_swap wreath_body.
Proof.
  repeat split.
  - unfold deduced. vm_compute. discriminate.
  - apply uniform_symmetry_is_automorphism. reflexivity.
Qed.

(* ===================================================================== *)
(* PART E.  YOUNG SUBGROUPS ARE GENERATED BY THEIR ADJACENT              *)
(* TRANSPOSITIONS, in the tower's list semantics: BladeDeduce's          *)
(* adjacent_transpositions_generate, from one block to a shape.  A list  *)
(* function that cannot see a swap at any INTERIOR position of any block *)
(* cannot see any blockwise permutation.                                 *)
(* ===================================================================== *)

Section YoungGeneration.
  Variables T W : Type.
  Variable f : list T -> W.
  Variable P : nat -> Prop.
  Hypothesis Hpos : forall pre (a b : T) post, P (length pre) ->
    f (pre ++ a :: b :: post) = f (pre ++ b :: a :: post).

  Lemma block_perm : forall blk blk', Permutation blk blk' ->
    forall pre post,
    (forall i, length pre <= i -> S i < length pre + length blk -> P i) ->
    f (pre ++ blk ++ post) = f (pre ++ blk' ++ post).
  Proof.
    intros blk blk' HP.
    induction HP as [| x l1 l2 HP IH | x y l1 | l1 l2 l3 HP1 IH1 HP2 IH2];
      intros pre post Hin.
    - reflexivity.
    - change (pre ++ (x :: l1) ++ post) with (pre ++ [x] ++ l1 ++ post).
      change (pre ++ (x :: l2) ++ post) with (pre ++ [x] ++ l2 ++ post).
      rewrite !(app_assoc pre [x]). apply IH.
      intros i H1 H2. rewrite app_length in H1, H2. simpl in H1, H2.
      apply Hin; simpl; lia.
    - simpl. apply Hpos. apply Hin; simpl; lia.
    - rewrite IH1 by exact Hin. apply IH2.
      intros i H1 H2. apply Hin; [exact H1 |].
      rewrite (Permutation_length HP1). exact H2.
  Qed.

  Inductive bperm : list nat -> list T -> list T -> Prop :=
  | bperm_nil : forall l, bperm [] l l
  | bperm_cons : forall n bs b b' r r',
      length b = n -> Permutation b b' -> bperm bs r r' ->
      bperm (n :: bs) (b ++ r) (b' ++ r').

  Fixpoint interior (off : nat) (bs : list nat) (i : nat) : Prop :=
    match bs with
    | [] => False
    | n :: bs' => (off <= i /\ S i < off + n) \/ interior (off + n) bs' i
    end.

  Lemma young_generated_ctx : forall bs l l', bperm bs l l' ->
    forall pre, (forall i, interior (length pre) bs i -> P i) ->
    f (pre ++ l) = f (pre ++ l').
  Proof.
    intros bs l l' H.
    induction H as [l | n bs b b' r r' Hn HP _ IH]; intros pre Hin.
    - reflexivity.
    - rewrite (block_perm b b' HP pre r).
      + rewrite !app_assoc. apply IH.
        intros i Hi. apply Hin. right.
        rewrite app_length, <- (Permutation_length HP), Hn in Hi. exact Hi.
      + intros i H1 H2. apply Hin. left. rewrite Hn in H2. split; assumption.
  Qed.

  Theorem young_generated : forall bs l l',
    (forall i, interior 0 bs i -> P i) -> bperm bs l l' -> f l = f l'.
  Proof.
    intros bs l l' Hin H. exact (young_generated_ctx bs l l' H [] Hin).
  Qed.
End YoungGeneration.
